### ISSUE TITLE
Clicking on Validator links produce an error

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/frontend-monorepo#3692]
Opened token FE on browser (chrome) - mainnet
Connected desktop wallet
Navigated to the list of validators I am staked to
Clicked on the validator names

This was then shown

<img width="668" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/86229849/ca5d5d6e-19a2-4ccd-af33-d63e805fc8d5">

Dev tools/console contained this error

```
caught SyntaxError: Unexpected token '<'
main.e0f242315775fd5f.esm.js:1116 ChunkLoadError: Loading chunk 887 failed.
(missing: https://governance.vega.xyz/route-staking-node.dade68fcacf97328.esm.js)
    at c.f.j (runtime.c2b13fd53a56d762.esm.js:1:4835)
    at runtime.c2b13fd53a56d762.esm.js:1:1281
    at Array.reduce (<anonymous>)
    at c.e (runtime.c2b13fd53a56d762.esm.js:1:1259)
    at main.e0f242315775fd5f.esm.js:56:4268
    at x (main.e0f242315775fd5f.esm.js:1116:3491971)
    at Sl (main.e0f242315775fd5f.esm.js:1116:3452514)
    at yc (main.e0f242315775fd5f.esm.js:1116:3441024)
    at _c (main.e0f242315775fd5f.esm.js:1116:3440996)
    at ic (main.e0f242315775fd5f.esm.js:1116:3436046)
    at w (main.e0f242315775fd5f.esm.js:1116:3617908)
    at I (main.e0f242315775fd5f.esm.js:1116:3618440)
    at O.<computed> (task.js:61:7)
    at T (task.js:35:5)
    at MessagePort.P (task.js:46:3)
(
```

**Comment by dexturr** [comment]
Race condition due to a release going out during the time user was on the site, chunking meant the bundle requested a previous chunk that no longer existed on CDN. Should be fixed more properly, but not urgent.
