### ISSUE TITLE
Unhandled exception after swapping markets

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5754]
## Description
Unhandled exeception when i try to open a new market while using locally served console (develop branch)

## Steps to Reproduce

1. Build and Serve console (develop branch)
2. Click on 'market selector
3. Click on a different market
`ag-grid-community.auto.esm.js:35980 Uncaught TypeError: Cannot read properties of null (reading 'getColId')
    at HeaderCellCtrl.getColId (ag-grid-community.auto.esm.js:35980:1)
    at HeaderCellComp (headerCellComp.js:42:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at updateSimpleMemoComponent (react-dom.development.js:19425:1)
    at beginWork (react-dom.development.js:21678:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at commitRootImpl (react-dom.development.js:26959:1)
    at commitRoot (react-dom.development.js:26682:1)
    at finishConcurrentRender (react-dom.development.js:25981:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25809:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)`
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/296744c9-5ae0-4f63-8024-4b7e8798bb67)

**Comment by JonRay15** [comment]
@bwallacee can this possibly impact mainnet?  If not we're going to push out
